name: hidapi
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  ffigen: ^1.2.0
  ffi: ^0.1.3
  convert: ^2.1.1

ffigen:
  name: HidApi
  description: Bindings to `hidapi.h`.
  output: 'lib/hidapi.dart'
  compiler-opts: '-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Headers/'
  headers:
    entry-points:
      - 'hidapi/hidapi.h'
    include-directives: # include only these header files and necessary structs from other header files
      - '**hidapi.h'
