// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `hidapi.h`.
class HidApi {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  HidApi(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  /// @brief Initialize the HIDAPI library.
  ///
  /// This function initializes the HIDAPI library. Calling it is not
  /// strictly necessary, as it will be called automatically by
  /// hid_enumerate() and any of the hid_open_*() functions if it is
  /// needed.  This function should be called at the beginning of
  /// execution however, if there is a chance of HIDAPI handles
  /// being opened by different threads simultaneously.
  ///
  /// @ingroup API
  ///
  /// @returns
  /// This function returns 0 on success and -1 on error.
  int hid_init() {
    _hid_init ??=
        _dylib.lookupFunction<_c_hid_init, _dart_hid_init>('hid_init');
    return _hid_init();
  }

  _dart_hid_init _hid_init;

  /// @brief Finalize the HIDAPI library.
  ///
  /// This function frees all of the static data associated with
  /// HIDAPI. It should be called at the end of execution to avoid
  /// memory leaks.
  ///
  /// @ingroup API
  ///
  /// @returns
  /// This function returns 0 on success and -1 on error.
  int hid_exit() {
    _hid_exit ??=
        _dylib.lookupFunction<_c_hid_exit, _dart_hid_exit>('hid_exit');
    return _hid_exit();
  }

  _dart_hid_exit _hid_exit;

  /// @brief Enumerate the HID Devices.
  ///
  /// This function returns a linked list of all the HID devices
  /// attached to the system which match vendor_id and product_id.
  /// If @p vendor_id is set to 0 then any vendor matches.
  /// If @p product_id is set to 0 then any product matches.
  /// If @p vendor_id and @p product_id are both set to 0, then
  /// all HID devices will be returned.
  ///
  /// @ingroup API
  /// @param vendor_id The Vendor ID (VID) of the types of device
  /// to open.
  /// @param product_id The Product ID (PID) of the types of
  /// device to open.
  ///
  /// @returns
  /// This function returns a pointer to a linked list of type
  /// struct #hid_device_info, containing information about the HID devices
  /// attached to the system, or NULL in the case of failure. Free
  /// this linked list by calling hid_free_enumeration().
  ffi.Pointer<hid_device_info> hid_enumerate(
    int vendor_id,
    int product_id,
  ) {
    _hid_enumerate ??= _dylib
        .lookupFunction<_c_hid_enumerate, _dart_hid_enumerate>('hid_enumerate');
    return _hid_enumerate(
      vendor_id,
      product_id,
    );
  }

  _dart_hid_enumerate _hid_enumerate;

  /// @brief Free an enumeration Linked List
  ///
  /// This function frees a linked list created by hid_enumerate().
  ///
  /// @ingroup API
  /// @param devs Pointer to a list of struct_device returned from
  /// hid_enumerate().
  void hid_free_enumeration(
    ffi.Pointer<hid_device_info> devs,
  ) {
    _hid_free_enumeration ??= _dylib.lookupFunction<_c_hid_free_enumeration,
        _dart_hid_free_enumeration>('hid_free_enumeration');
    return _hid_free_enumeration(
      devs,
    );
  }

  _dart_hid_free_enumeration _hid_free_enumeration;

  /// @brief Open a HID device using a Vendor ID (VID), Product ID
  /// (PID) and optionally a serial number.
  ///
  /// If @p serial_number is NULL, the first device with the
  /// specified VID and PID is opened.
  ///
  /// This function sets the return value of hid_error().
  ///
  /// @ingroup API
  /// @param vendor_id The Vendor ID (VID) of the device to open.
  /// @param product_id The Product ID (PID) of the device to open.
  /// @param serial_number The Serial Number of the device to open
  /// (Optionally NULL).
  ///
  /// @returns
  /// This function returns a pointer to a #hid_device object on
  /// success or NULL on failure.
  ffi.Pointer<hid_device_> hid_open(
    int vendor_id,
    int product_id,
    ffi.Pointer<ffi.Int32> serial_number,
  ) {
    _hid_open ??=
        _dylib.lookupFunction<_c_hid_open, _dart_hid_open>('hid_open');
    return _hid_open(
      vendor_id,
      product_id,
      serial_number,
    );
  }

  _dart_hid_open _hid_open;

  /// @brief Open a HID device by its path name.
  ///
  /// The path name be determined by calling hid_enumerate(), or a
  /// platform-specific path name can be used (eg: /dev/hidraw0 on
  /// Linux).
  ///
  /// This function sets the return value of hid_error().
  ///
  /// @ingroup API
  /// @param path The path name of the device to open
  ///
  /// @returns
  /// This function returns a pointer to a #hid_device object on
  /// success or NULL on failure.
  ffi.Pointer<hid_device_> hid_open_path(
    ffi.Pointer<ffi.Int8> path,
  ) {
    _hid_open_path ??= _dylib
        .lookupFunction<_c_hid_open_path, _dart_hid_open_path>('hid_open_path');
    return _hid_open_path(
      path,
    );
  }

  _dart_hid_open_path _hid_open_path;

  /// @brief Write an Output report to a HID device.
  ///
  /// The first byte of @p data[] must contain the Report ID. For
  /// devices which only support a single report, this must be set
  /// to 0x0. The remaining bytes contain the report data. Since
  /// the Report ID is mandatory, calls to hid_write() will always
  /// contain one more byte than the report contains. For example,
  /// if a hid report is 16 bytes long, 17 bytes must be passed to
  /// hid_write(), the Report ID (or 0x0, for devices with a
  /// single report), followed by the report data (16 bytes). In
  /// this example, the length passed in would be 17.
  ///
  /// hid_write() will send the data on the first OUT endpoint, if
  /// one exists. If it does not, it will send the data through
  /// the Control Endpoint (Endpoint 0).
  ///
  /// This function sets the return value of hid_error().
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param data The data to send, including the report number as
  /// the first byte.
  /// @param length The length in bytes of the data to send.
  ///
  /// @returns
  /// This function returns the actual number of bytes written and
  /// -1 on error.
  int hid_write(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Uint8> data,
    int length,
  ) {
    _hid_write ??=
        _dylib.lookupFunction<_c_hid_write, _dart_hid_write>('hid_write');
    return _hid_write(
      dev,
      data,
      length,
    );
  }

  _dart_hid_write _hid_write;

  /// @brief Read an Input report from a HID device with timeout.
  ///
  /// Input reports are returned
  /// to the host through the INTERRUPT IN endpoint. The first byte will
  /// contain the Report number if the device uses numbered reports.
  ///
  /// This function sets the return value of hid_error().
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param data A buffer to put the read data into.
  /// @param length The number of bytes to read. For devices with
  /// multiple reports, make sure to read an extra byte for
  /// the report number.
  /// @param milliseconds timeout in milliseconds or -1 for blocking wait.
  ///
  /// @returns
  /// This function returns the actual number of bytes read and
  /// -1 on error. If no packet was available to be read within
  /// the timeout period, this function returns 0.
  int hid_read_timeout(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Uint8> data,
    int length,
    int milliseconds,
  ) {
    _hid_read_timeout ??=
        _dylib.lookupFunction<_c_hid_read_timeout, _dart_hid_read_timeout>(
            'hid_read_timeout');
    return _hid_read_timeout(
      dev,
      data,
      length,
      milliseconds,
    );
  }

  _dart_hid_read_timeout _hid_read_timeout;

  /// @brief Read an Input report from a HID device.
  ///
  /// Input reports are returned
  /// to the host through the INTERRUPT IN endpoint. The first byte will
  /// contain the Report number if the device uses numbered reports.
  ///
  /// This function sets the return value of hid_error().
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param data A buffer to put the read data into.
  /// @param length The number of bytes to read. For devices with
  /// multiple reports, make sure to read an extra byte for
  /// the report number.
  ///
  /// @returns
  /// This function returns the actual number of bytes read and
  /// -1 on error. If no packet was available to be read and
  /// the handle is in non-blocking mode, this function returns 0.
  int hid_read(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Uint8> data,
    int length,
  ) {
    _hid_read ??=
        _dylib.lookupFunction<_c_hid_read, _dart_hid_read>('hid_read');
    return _hid_read(
      dev,
      data,
      length,
    );
  }

  _dart_hid_read _hid_read;

  /// @brief Set the device handle to be non-blocking.
  ///
  /// In non-blocking mode calls to hid_read() will return
  /// immediately with a value of 0 if there is no data to be
  /// read. In blocking mode, hid_read() will wait (block) until
  /// there is data to read before returning.
  ///
  /// Nonblocking can be turned on and off at any time.
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param nonblock enable or not the nonblocking reads
  /// - 1 to enable nonblocking
  /// - 0 to disable nonblocking.
  ///
  /// @returns
  /// This function returns 0 on success and -1 on error.
  int hid_set_nonblocking(
    ffi.Pointer<hid_device_> dev,
    int nonblock,
  ) {
    _hid_set_nonblocking ??= _dylib.lookupFunction<_c_hid_set_nonblocking,
        _dart_hid_set_nonblocking>('hid_set_nonblocking');
    return _hid_set_nonblocking(
      dev,
      nonblock,
    );
  }

  _dart_hid_set_nonblocking _hid_set_nonblocking;

  /// @brief Send a Feature report to the device.
  ///
  /// Feature reports are sent over the Control endpoint as a
  /// Set_Report transfer.  The first byte of @p data[] must
  /// contain the Report ID. For devices which only support a
  /// single report, this must be set to 0x0. The remaining bytes
  /// contain the report data. Since the Report ID is mandatory,
  /// calls to hid_send_feature_report() will always contain one
  /// more byte than the report contains. For example, if a hid
  /// report is 16 bytes long, 17 bytes must be passed to
  /// hid_send_feature_report(): the Report ID (or 0x0, for
  /// devices which do not use numbered reports), followed by the
  /// report data (16 bytes). In this example, the length passed
  /// in would be 17.
  ///
  /// This function sets the return value of hid_error().
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param data The data to send, including the report number as
  /// the first byte.
  /// @param length The length in bytes of the data to send, including
  /// the report number.
  ///
  /// @returns
  /// This function returns the actual number of bytes written and
  /// -1 on error.
  int hid_send_feature_report(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Uint8> data,
    int length,
  ) {
    _hid_send_feature_report ??= _dylib.lookupFunction<
        _c_hid_send_feature_report,
        _dart_hid_send_feature_report>('hid_send_feature_report');
    return _hid_send_feature_report(
      dev,
      data,
      length,
    );
  }

  _dart_hid_send_feature_report _hid_send_feature_report;

  /// @brief Get a feature report from a HID device.
  ///
  /// Set the first byte of @p data[] to the Report ID of the
  /// report to be read.  Make sure to allow space for this
  /// extra byte in @p data[]. Upon return, the first byte will
  /// still contain the Report ID, and the report data will
  /// start in data[1].
  ///
  /// This function sets the return value of hid_error().
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param data A buffer to put the read data into, including
  /// the Report ID. Set the first byte of @p data[] to the
  /// Report ID of the report to be read, or set it to zero
  /// if your device does not use numbered reports.
  /// @param length The number of bytes to read, including an
  /// extra byte for the report ID. The buffer can be longer
  /// than the actual report.
  ///
  /// @returns
  /// This function returns the number of bytes read plus
  /// one for the report ID (which is still in the first
  /// byte), or -1 on error.
  int hid_get_feature_report(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Uint8> data,
    int length,
  ) {
    _hid_get_feature_report ??= _dylib.lookupFunction<_c_hid_get_feature_report,
        _dart_hid_get_feature_report>('hid_get_feature_report');
    return _hid_get_feature_report(
      dev,
      data,
      length,
    );
  }

  _dart_hid_get_feature_report _hid_get_feature_report;

  /// @brief Get a input report from a HID device.
  ///
  /// Set the first byte of @p data[] to the Report ID of the
  /// report to be read. Make sure to allow space for this
  /// extra byte in @p data[]. Upon return, the first byte will
  /// still contain the Report ID, and the report data will
  /// start in data[1].
  ///
  /// @ingroup API
  /// @param device A device handle returned from hid_open().
  /// @param data A buffer to put the read data into, including
  /// the Report ID. Set the first byte of @p data[] to the
  /// Report ID of the report to be read, or set it to zero
  /// if your device does not use numbered reports.
  /// @param length The number of bytes to read, including an
  /// extra byte for the report ID. The buffer can be longer
  /// than the actual report.
  ///
  /// @returns
  /// This function returns the number of bytes read plus
  /// one for the report ID (which is still in the first
  /// byte), or -1 on error.
  int hid_get_input_report(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Uint8> data,
    int length,
  ) {
    _hid_get_input_report ??= _dylib.lookupFunction<_c_hid_get_input_report,
        _dart_hid_get_input_report>('hid_get_input_report');
    return _hid_get_input_report(
      dev,
      data,
      length,
    );
  }

  _dart_hid_get_input_report _hid_get_input_report;

  /// @brief Close a HID device.
  ///
  /// This function sets the return value of hid_error().
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  void hid_close(
    ffi.Pointer<hid_device_> dev,
  ) {
    _hid_close ??=
        _dylib.lookupFunction<_c_hid_close, _dart_hid_close>('hid_close');
    return _hid_close(
      dev,
    );
  }

  _dart_hid_close _hid_close;

  /// @brief Get The Manufacturer String from a HID device.
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param string A wide string buffer to put the data into.
  /// @param maxlen The length of the buffer in multiples of wchar_t.
  ///
  /// @returns
  /// This function returns 0 on success and -1 on error.
  int hid_get_manufacturer_string(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Int32> string,
    int maxlen,
  ) {
    _hid_get_manufacturer_string ??= _dylib.lookupFunction<
        _c_hid_get_manufacturer_string,
        _dart_hid_get_manufacturer_string>('hid_get_manufacturer_string');
    return _hid_get_manufacturer_string(
      dev,
      string,
      maxlen,
    );
  }

  _dart_hid_get_manufacturer_string _hid_get_manufacturer_string;

  /// @brief Get The Product String from a HID device.
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param string A wide string buffer to put the data into.
  /// @param maxlen The length of the buffer in multiples of wchar_t.
  ///
  /// @returns
  /// This function returns 0 on success and -1 on error.
  int hid_get_product_string(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Int32> string,
    int maxlen,
  ) {
    _hid_get_product_string ??= _dylib.lookupFunction<_c_hid_get_product_string,
        _dart_hid_get_product_string>('hid_get_product_string');
    return _hid_get_product_string(
      dev,
      string,
      maxlen,
    );
  }

  _dart_hid_get_product_string _hid_get_product_string;

  /// @brief Get The Serial Number String from a HID device.
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param string A wide string buffer to put the data into.
  /// @param maxlen The length of the buffer in multiples of wchar_t.
  ///
  /// @returns
  /// This function returns 0 on success and -1 on error.
  int hid_get_serial_number_string(
    ffi.Pointer<hid_device_> dev,
    ffi.Pointer<ffi.Int32> string,
    int maxlen,
  ) {
    _hid_get_serial_number_string ??= _dylib.lookupFunction<
        _c_hid_get_serial_number_string,
        _dart_hid_get_serial_number_string>('hid_get_serial_number_string');
    return _hid_get_serial_number_string(
      dev,
      string,
      maxlen,
    );
  }

  _dart_hid_get_serial_number_string _hid_get_serial_number_string;

  /// @brief Get a string from a HID device, based on its string index.
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open().
  /// @param string_index The index of the string to get.
  /// @param string A wide string buffer to put the data into.
  /// @param maxlen The length of the buffer in multiples of wchar_t.
  ///
  /// @returns
  /// This function returns 0 on success and -1 on error.
  int hid_get_indexed_string(
    ffi.Pointer<hid_device_> dev,
    int string_index,
    ffi.Pointer<ffi.Int32> string,
    int maxlen,
  ) {
    _hid_get_indexed_string ??= _dylib.lookupFunction<_c_hid_get_indexed_string,
        _dart_hid_get_indexed_string>('hid_get_indexed_string');
    return _hid_get_indexed_string(
      dev,
      string_index,
      string,
      maxlen,
    );
  }

  _dart_hid_get_indexed_string _hid_get_indexed_string;

  /// @brief Get a string describing the last error which occurred.
  ///
  /// Whether a function sets the last error is noted in its
  /// documentation. These functions will reset the last error
  /// to NULL before their execution.
  ///
  /// Strings returned from hid_error() must not be freed by the user!
  ///
  /// This function is thread-safe, and error messages are thread-local.
  ///
  /// @ingroup API
  /// @param dev A device handle returned from hid_open(),
  /// or NULL to get the last non-device-specific error
  /// (e.g. for errors in hid_open() itself).
  ///
  /// @returns
  /// This function returns a string containing the last error
  /// which occurred or NULL if none has occurred.
  ffi.Pointer<ffi.Int32> hid_error(
    ffi.Pointer<hid_device_> dev,
  ) {
    _hid_error ??=
        _dylib.lookupFunction<_c_hid_error, _dart_hid_error>('hid_error');
    return _hid_error(
      dev,
    );
  }

  _dart_hid_error _hid_error;

  /// @brief Get a runtime version of the library.
  ///
  /// @ingroup API
  ///
  /// @returns
  /// Pointer to statically allocated struct, that contains version.
  ffi.Pointer<hid_api_version> hid_version() {
    _hid_version ??=
        _dylib.lookupFunction<_c_hid_version, _dart_hid_version>('hid_version');
    return _hid_version();
  }

  _dart_hid_version _hid_version;

  /// @brief Get a runtime version string of the library.
  ///
  /// @ingroup API
  ///
  /// @returns
  /// Pointer to statically allocated string, that contains version string.
  ffi.Pointer<ffi.Int8> hid_version_str() {
    _hid_version_str ??=
        _dylib.lookupFunction<_c_hid_version_str, _dart_hid_version_str>(
            'hid_version_str');
    return _hid_version_str();
  }

  _dart_hid_version_str _hid_version_str;
}

class hid_api_version extends ffi.Struct {
  @ffi.Int32()
  int major;

  @ffi.Int32()
  int minor;

  @ffi.Int32()
  int patch;
}

class hid_device_ extends ffi.Struct {}

/// hidapi info structure
class hid_device_info extends ffi.Struct {
  /// Platform-specific device path
  ffi.Pointer<ffi.Int8> path;

  /// Device Vendor ID
  @ffi.Uint16()
  int vendor_id;

  /// Device Product ID
  @ffi.Uint16()
  int product_id;

  /// Serial Number
  ffi.Pointer<ffi.Int32> serial_number;

  /// Device Release Number in binary-coded decimal,
  /// also known as Device Version Number
  @ffi.Uint16()
  int release_number;

  /// Manufacturer String
  ffi.Pointer<ffi.Int32> manufacturer_string;

  /// Product string
  ffi.Pointer<ffi.Int32> product_string;

  /// Usage Page for this Device/Interface
  /// (Windows/Mac/hidraw only)
  @ffi.Uint16()
  int usage_page;

  /// Usage for this Device/Interface
  /// (Windows/Mac/hidraw only)
  @ffi.Uint16()
  int usage;

  /// The USB interface which this logical device
  /// represents.
  ///
  /// Valid on both Linux implementations in all cases.
  /// Valid on the Windows implementation only if the device
  /// contains more than one interface.
  /// Valid on the Mac implementation if and only if the device
  /// is a USB HID device.
  @ffi.Int32()
  int interface_number;

  /// Pointer to the next device
  ffi.Pointer<hid_device_info> next;
}

const int HID_API_VERSION_MAJOR = 0;

const int HID_API_VERSION_MINOR = 10;

const int HID_API_VERSION_PATCH = 1;

const String HID_API_VERSION_STR = '0.10.1';

typedef _c_hid_init = ffi.Int32 Function();

typedef _dart_hid_init = int Function();

typedef _c_hid_exit = ffi.Int32 Function();

typedef _dart_hid_exit = int Function();

typedef _c_hid_enumerate = ffi.Pointer<hid_device_info> Function(
  ffi.Uint16 vendor_id,
  ffi.Uint16 product_id,
);

typedef _dart_hid_enumerate = ffi.Pointer<hid_device_info> Function(
  int vendor_id,
  int product_id,
);

typedef _c_hid_free_enumeration = ffi.Void Function(
  ffi.Pointer<hid_device_info> devs,
);

typedef _dart_hid_free_enumeration = void Function(
  ffi.Pointer<hid_device_info> devs,
);

typedef _c_hid_open = ffi.Pointer<hid_device_> Function(
  ffi.Uint16 vendor_id,
  ffi.Uint16 product_id,
  ffi.Pointer<ffi.Int32> serial_number,
);

typedef _dart_hid_open = ffi.Pointer<hid_device_> Function(
  int vendor_id,
  int product_id,
  ffi.Pointer<ffi.Int32> serial_number,
);

typedef _c_hid_open_path = ffi.Pointer<hid_device_> Function(
  ffi.Pointer<ffi.Int8> path,
);

typedef _dart_hid_open_path = ffi.Pointer<hid_device_> Function(
  ffi.Pointer<ffi.Int8> path,
);

typedef _c_hid_write = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  ffi.Uint64 length,
);

typedef _dart_hid_write = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  int length,
);

typedef _c_hid_read_timeout = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  ffi.Uint64 length,
  ffi.Int32 milliseconds,
);

typedef _dart_hid_read_timeout = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  int length,
  int milliseconds,
);

typedef _c_hid_read = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  ffi.Uint64 length,
);

typedef _dart_hid_read = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  int length,
);

typedef _c_hid_set_nonblocking = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Int32 nonblock,
);

typedef _dart_hid_set_nonblocking = int Function(
  ffi.Pointer<hid_device_> dev,
  int nonblock,
);

typedef _c_hid_send_feature_report = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  ffi.Uint64 length,
);

typedef _dart_hid_send_feature_report = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  int length,
);

typedef _c_hid_get_feature_report = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  ffi.Uint64 length,
);

typedef _dart_hid_get_feature_report = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  int length,
);

typedef _c_hid_get_input_report = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  ffi.Uint64 length,
);

typedef _dart_hid_get_input_report = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Uint8> data,
  int length,
);

typedef _c_hid_close = ffi.Void Function(
  ffi.Pointer<hid_device_> dev,
);

typedef _dart_hid_close = void Function(
  ffi.Pointer<hid_device_> dev,
);

typedef _c_hid_get_manufacturer_string = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Int32> string,
  ffi.Uint64 maxlen,
);

typedef _dart_hid_get_manufacturer_string = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Int32> string,
  int maxlen,
);

typedef _c_hid_get_product_string = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Int32> string,
  ffi.Uint64 maxlen,
);

typedef _dart_hid_get_product_string = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Int32> string,
  int maxlen,
);

typedef _c_hid_get_serial_number_string = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Int32> string,
  ffi.Uint64 maxlen,
);

typedef _dart_hid_get_serial_number_string = int Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Pointer<ffi.Int32> string,
  int maxlen,
);

typedef _c_hid_get_indexed_string = ffi.Int32 Function(
  ffi.Pointer<hid_device_> dev,
  ffi.Int32 string_index,
  ffi.Pointer<ffi.Int32> string,
  ffi.Uint64 maxlen,
);

typedef _dart_hid_get_indexed_string = int Function(
  ffi.Pointer<hid_device_> dev,
  int string_index,
  ffi.Pointer<ffi.Int32> string,
  int maxlen,
);

typedef _c_hid_error = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<hid_device_> dev,
);

typedef _dart_hid_error = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<hid_device_> dev,
);

typedef _c_hid_version = ffi.Pointer<hid_api_version> Function();

typedef _dart_hid_version = ffi.Pointer<hid_api_version> Function();

typedef _c_hid_version_str = ffi.Pointer<ffi.Int8> Function();

typedef _dart_hid_version_str = ffi.Pointer<ffi.Int8> Function();
